package com.example.photoweather.models;


import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * @author Ali Adel
 * <p>
 * Hold photo object and representation in DB with table name "photo_table"
 */
@Entity(tableName = "photo_table")
public class Photo {

    // primary key for DB
    @PrimaryKey(autoGenerate = true)
    private int id;

    // url which holds location of photo in device
    private String url;

    // time in which photo was taken to order photos from DB
    private String timeStamp;

    /**
     * Constructor to use in Main Activity when making photo objects and
     * Room also uses it to make objects
     *
     * @param url       location of photo in device
     * @param timeStamp time photo was taken to order photos from DB
     */
    public Photo(String url, String timeStamp) {
        this.url = url;
        this.timeStamp = timeStamp;
    }

    /**
     * Only used by Room to make Photo objects with id to put in DB
     *
     * @param id id generated by DB
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return returns object ID
     */
    public int getId() {
        return id;
    }

    /**
     * @return url of photo
     */
    public String getUrl() {
        return url;
    }

    /**
     * @return time stamp of photo
     */
    public String getTimeStamp() {
        return timeStamp;
    }
}
